apiVersion: v1
kind: Service
metadata:
  name: relay-user-service
  namespace: relay
spec:
  type: ClusterIP
  selector:
    app: relay-user-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 9090
      targetPort: 9090