apiVersion: v1
kind: Service
metadata:
  name: relay-message-service
  namespace: relay
spec:
  type: ClusterIP
  selector:
    app: relay-message-service
  ports:
    - port: 8083
      targetPort: 8083